import {
  HouseholdDTO,
  ChoreDTO,
  ChoreAssignmentDTO,
  MemberDTO,
  LookupCategoryDTO,
  LookupFrequencyDTO,
  TemplateChoreDTO,
} from "@chore-champ/types";

export const householdSeeds: HouseholdDTO[] = [
  {
    id: "house_001",
    name: "Vo Household",
    memberCount: 3,
    bathroomCount: 2,
    bedroomCount: 3,
    hasAttic: false,
    hasBasement: true,
    hasDiningArea: true,
    hasDriveway: true,
    hasGarage: true,
    hasLaundryRoom: true,
    hasOffice: true,
    hasYard: true,
    hasHallway: true,
    hasLivingRoom: true,
  },
  {
    id: "house_002",
    name: "Downtown Condo",
    memberCount: 2,
    bathroomCount: 1,
    bedroomCount: 1,
    hasAttic: false,
    hasBasement: false,
    hasDiningArea: false,
    hasDriveway: false,
    hasGarage: false,
    hasLaundryRoom: false,
    hasOffice: false,
    hasYard: false,
    hasHallway: false,
    hasLivingRoom: true,
  },
  {
    id: "house_003",
    name: "Suburban Family Home",
    memberCount: 4,
    bathroomCount: 3,
    bedroomCount: 4,
    hasAttic: true,
    hasBasement: true,
    hasDiningArea: true,
    hasDriveway: true,
    hasGarage: true,
    hasLaundryRoom: true,
    hasOffice: true,
    hasYard: true,
    hasHallway: true,
    hasLivingRoom: true,
  },
];

export const memberSeeds: MemberDTO[] = [
  {
    id: "member_001",
    householdId: "house_001",
    name: "Phong",
    role: "adult",
    isAdmin: true,
    isActive: true,
  },
  {
    id: "member_002",
    householdId: "house_001",
    name: "Raj",
    role: "adult",
    isAdmin: true,
    isActive: true,
  },
  {
    id: "member_003",
    householdId: "house_001",
    name: "Dad",
    role: "adult",
    isAdmin: false,
    isActive: true,
  },
];

export const choreSeeds: ChoreDTO[] = [
  {
    id: "bathroom-wash-towels-bath-mats",
    label: "Wash towels/bath mats",
    categoryId: "bathroom",
    frequencyId: "weekly",
    pts: 1,
  },

  {
    id: "bedroom-organize-nightstand",
    label: "Organize nightstand",
    categoryId: "bedroom",
    frequencyId: "monthly",
    pts: 2,
  },
  { id: "bedroom-rotate-mattress", label: "Rotate mattress", categoryId: "bedroom", frequencyId: "quarterly", pts: 3 },

  {
    id: "dining-area-clean-dining-chairs",
    label: "Clean dining chairs",
    categoryId: "dining-area",
    frequencyId: "weekly",
    pts: 1,
  },
  {
    id: "dining-area-polish-dining-table",
    label: "Polish dining table",
    categoryId: "dining-area",
    frequencyId: "monthly",
    pts: 2,
  },
  {
    id: "dining-area-clean-dining-light-fixture",
    label: "Clean dining light fixture",
    categoryId: "dining-area",
    frequencyId: "monthly",
    pts: 2,
  },
  {
    id: "dining-area-organize-dining-storage",
    label: "Organize dining storage",
    categoryId: "dining-area",
    frequencyId: "quarterly",
    pts: 3,
  },

  { id: "garage-sweep-floor", label: "Sweep floor", categoryId: "garage", frequencyId: "monthly", pts: 2 },
  {
    id: "garage-organize-tools-supplies",
    label: "Organize tools/supplies",
    categoryId: "garage",
    frequencyId: "monthly",
    pts: 3,
  },
  {
    id: "garage-check-garage-storage-bins",
    label: "Check garage storage bins",
    categoryId: "garage",
    frequencyId: "quarterly",
    pts: 2,
  },
  {
    id: "garage-wipe-garage-workbench",
    label: "Wipe garage workbench",
    categoryId: "garage",
    frequencyId: "monthly",
    pts: 2,
  },

  {
    id: "hallway-clean-walls-light-switches",
    label: "Clean walls/light switches",
    categoryId: "hallway",
    frequencyId: "monthly",
    pts: 2,
  },
  {
    id: "hallway-organize-hallway-closet",
    label: "Organize hallway closet",
    categoryId: "hallway",
    frequencyId: "quarterly",
    pts: 3,
  },

  { id: "house-wipe-glass-doors", label: "Wipe glass doors", categoryId: "house", frequencyId: "monthly", pts: 2 },
  { id: "house-vacuum-vents", label: "Vacuum vents", categoryId: "house", frequencyId: "quarterly", pts: 2 },
  {
    id: "house-replace-air-filter",
    label: "Replace air filter",
    categoryId: "house",
    frequencyId: "quarterly",
    pts: 3,
  },
  {
    id: "house-wipe-electronics-remotes",
    label: "Wipe electronics/remotes",
    categoryId: "house",
    frequencyId: "weekly",
    pts: 2,
  },

  {
    id: "kitchen-clean-sink-and-faucet",
    label: "Clean sink and faucet",
    categoryId: "kitchen",
    frequencyId: "daily",
    pts: 1,
  },
  {
    id: "kitchen-empty-trash-and-recycling",
    label: "Empty trash and recycling",
    categoryId: "kitchen",
    frequencyId: "daily",
    pts: 1,
  },
  {
    id: "kitchen-clean-stovetop-burners",
    label: "Clean stovetop burners",
    categoryId: "kitchen",
    frequencyId: "monthly",
    pts: 2,
  },
  {
    id: "kitchen-wipe-refrigerator-gasket",
    label: "Wipe refrigerator gasket",
    categoryId: "kitchen",
    frequencyId: "monthly",
    pts: 2,
  },

  {
    id: "laundry-room-check-laundry-supplies",
    label: "Check laundry supplies",
    categoryId: "laundry-room",
    frequencyId: "weekly",
    pts: 1,
  },

  { id: "living-room-dust-tv-stand", label: "Dust TV stand", categoryId: "living-room", frequencyId: "weekly", pts: 1 },

  { id: "yard-sweep-patio", label: "Sweep patio", categoryId: "yard", frequencyId: "weekly", pts: 2 },
  { id: "yard-clean-garden-tools", label: "Clean garden tools", categoryId: "yard", frequencyId: "monthly", pts: 2 },
  {
    id: "yard-check-irrigation-system",
    label: "Check irrigation system",
    categoryId: "yard",
    frequencyId: "monthly",
    pts: 3,
  },
  { id: "yard-clean-outdoor-grill", label: "Clean outdoor grill", categoryId: "yard", frequencyId: "monthly", pts: 3 },
];

export const choreAssignmentSeeds: ChoreAssignmentDTO[] = [
  {
    id: "assign_001",
    choreId: "kitchen-clean-sink-and-faucet",
    memberId: "member_001",
    frequencyId: "daily",
    pts: 1,
  },
  {
    id: "assign_002",
    choreId: "kitchen-empty-trash-and-recycling",
    memberId: "member_002",
    frequencyId: "daily",
    pts: 1,
  },
  {
    id: "assign_003",
    choreId: "bathroom-wash-towels-bath-mats",
    memberId: "member_002",
    frequencyId: "weekly",
    pts: 1,
  },
  {
    id: "assign_004",
    choreId: "living-room-dust-tv-stand",
    memberId: "member_003",
    frequencyId: "weekly",
    pts: 1,
  },
  {
    id: "assign_005",
    choreId: "garage-organize-tools-supplies",
    memberId: "member_003",
    frequencyId: "monthly",
    pts: 3,
  },
  {
    id: "assign_006",
    choreId: "bedroom-organize-nightstand",
    memberId: "member_001",
    frequencyId: "monthly",
    pts: 2,
  },
  {
    id: "assign_007",
    choreId: "yard-sweep-patio",
    memberId: "member_002",
    frequencyId: "weekly",
    pts: 2,
  },
  {
    id: "assign_008",
    choreId: "house-replace-air-filter",
    memberId: "member_003",
    frequencyId: "quarterly",
    pts: 3,
    labelOverride: "Replace HVAC filter",
  },
];

export const templateChoresSeeds: TemplateChoreDTO[] = [
  {
    id: "bathroom-wash-towels-bath-mats",
    defaultLabel: "Wash towels/bath mats",
    categoryId: "bathroom",
    defaultFrequencyId: "weekly",
    defaultPts: 1,
  },
  {
    id: "bathroom-wipe-sink-counter-mirror",
    defaultLabel: "Wipe sink/counter/mirror",
    categoryId: "bathroom",
    defaultFrequencyId: "daily",
    defaultPts: 2,
  },
  {
    id: "bathroom-mop-floor",
    defaultLabel: "Mop floor",
    categoryId: "bathroom",
    defaultFrequencyId: "weekly",
    defaultPts: 2,
  },
  {
    id: "bathroom-clean-toilet-bowl-seat",
    defaultLabel: "Clean toilet bowl/seat",
    categoryId: "bathroom",
    defaultFrequencyId: "weekly",
    defaultPts: 3,
  },
  {
    id: "bathroom-scrub-shower-tub-tiles",
    defaultLabel: "Scrub shower/tub/tiles",
    categoryId: "bathroom",
    defaultFrequencyId: "weekly",
    defaultPts: 3,
  },
  {
    id: "bathroom-clean-bathroom-mirror",
    defaultLabel: "Clean bathroom mirror",
    categoryId: "bathroom",
    defaultFrequencyId: "weekly",
    defaultPts: 1,
  },
  {
    id: "bathroom-restock-toilet-paper",
    defaultLabel: "Restock toilet paper",
    categoryId: "bathroom",
    defaultFrequencyId: "weekly",
    defaultPts: 1,
  },
  {
    id: "bathroom-empty-bathroom-trash",
    defaultLabel: "Empty bathroom trash",
    categoryId: "bathroom",
    defaultFrequencyId: "daily",
    defaultPts: 1,
  },
  {
    id: "bathroom-clean-shower-drain",
    defaultLabel: "Clean shower drain",
    categoryId: "bathroom",
    defaultFrequencyId: "monthly",
    defaultPts: 2,
  },
  {
    id: "bathroom-wash-shower-curtain",
    defaultLabel: "Wash shower curtain",
    categoryId: "bathroom",
    defaultFrequencyId: "quarterly",
    defaultPts: 3,
  },

  {
    id: "bedroom-change-sheets",
    defaultLabel: "Change sheets",
    categoryId: "bedroom",
    defaultFrequencyId: "weekly",
    defaultPts: 2,
  },
  {
    id: "bedroom-dust-surfaces",
    defaultLabel: "Dust surfaces",
    categoryId: "bedroom",
    defaultFrequencyId: "weekly",
    defaultPts: 2,
  },
  {
    id: "bedroom-vacuum-mop-floors",
    defaultLabel: "Vacuum/mop floors",
    categoryId: "bedroom",
    defaultFrequencyId: "weekly",
    defaultPts: 2,
  },
  {
    id: "bedroom-declutter-closets-drawers",
    defaultLabel: "Declutter closets/drawers",
    categoryId: "bedroom",
    defaultFrequencyId: "monthly",
    defaultPts: 3,
  },
  {
    id: "bedroom-make-bed",
    defaultLabel: "Make bed",
    categoryId: "bedroom",
    defaultFrequencyId: "daily",
    defaultPts: 1,
  },
  {
    id: "bedroom-open-windows-for-ventilation",
    defaultLabel: "Open windows for ventilation",
    categoryId: "bedroom",
    defaultFrequencyId: "daily",
    defaultPts: 1,
  },
  {
    id: "bedroom-wipe-bedside-tables",
    defaultLabel: "Wipe bedside tables",
    categoryId: "bedroom",
    defaultFrequencyId: "weekly",
    defaultPts: 1,
  },
  {
    id: "bedroom-organize-nightstand",
    defaultLabel: "Organize nightstand",
    categoryId: "bedroom",
    defaultFrequencyId: "monthly",
    defaultPts: 2,
  },
  {
    id: "bedroom-rotate-mattress",
    defaultLabel: "Rotate mattress",
    categoryId: "bedroom",
    defaultFrequencyId: "quarterly",
    defaultPts: 3,
  },

  {
    id: "dining-area-clean-dining-chairs",
    defaultLabel: "Clean dining chairs",
    categoryId: "dining-area",
    defaultFrequencyId: "weekly",
    defaultPts: 1,
  },
  {
    id: "dining-area-polish-dining-table",
    defaultLabel: "Polish dining table",
    categoryId: "dining-area",
    defaultFrequencyId: "monthly",
    defaultPts: 2,
  },
  {
    id: "dining-area-clean-dining-light-fixture",
    defaultLabel: "Clean dining light fixture",
    categoryId: "dining-area",
    defaultFrequencyId: "monthly",
    defaultPts: 2,
  },
  {
    id: "dining-area-organize-dining-storage",
    defaultLabel: "Organize dining storage",
    categoryId: "dining-area",
    defaultFrequencyId: "quarterly",
    defaultPts: 3,
  },
  {
    id: "dining-area-mop-floor",
    defaultLabel: "Mop floor",
    categoryId: "dining-area",
    defaultFrequencyId: "daily",
    defaultPts: 2,
  },
  {
    id: "dining-area-wipe-dining-table",
    defaultLabel: "Wipe dining table",
    categoryId: "dining-area",
    defaultFrequencyId: "daily",
    defaultPts: 1,
  },
  {
    id: "dining-area-sweep-floor",
    defaultLabel: "Sweep floor",
    categoryId: "dining-area",
    defaultFrequencyId: "daily",
    defaultPts: 2,
  },
  {
    id: "dining-area-dust-furniture-fixtures",
    defaultLabel: "Dust furniture/fixtures",
    categoryId: "dining-area",
    defaultFrequencyId: "weekly",
    defaultPts: 2,
  },
  {
    id: "dining-area-wash-table-linens",
    defaultLabel: "Wash table linens",
    categoryId: "dining-area",
    defaultFrequencyId: "weekly",
    defaultPts: 2,
  },

  {
    id: "garage-sweep-floor",
    defaultLabel: "Sweep floor",
    categoryId: "garage",
    defaultFrequencyId: "monthly",
    defaultPts: 2,
  },
  {
    id: "garage-organize-tools-supplies",
    defaultLabel: "Organize tools/supplies",
    categoryId: "garage",
    defaultFrequencyId: "monthly",
    defaultPts: 3,
  },
  {
    id: "garage-declutter-items",
    defaultLabel: "Declutter items",
    categoryId: "garage",
    defaultFrequencyId: "quarterly",
    defaultPts: 4,
  },
  {
    id: "garage-clean-garage-shelves",
    defaultLabel: "Clean garage shelves",
    categoryId: "garage",
    defaultFrequencyId: "monthly",
    defaultPts: 2,
  },
  {
    id: "garage-check-garage-storage-bins",
    defaultLabel: "Check garage storage bins",
    categoryId: "garage",
    defaultFrequencyId: "quarterly",
    defaultPts: 2,
  },
  {
    id: "garage-wipe-garage-workbench",
    defaultLabel: "Wipe garage workbench",
    categoryId: "garage",
    defaultFrequencyId: "monthly",
    defaultPts: 2,
  },

  {
    id: "hallway-clean-walls-light-switches",
    defaultLabel: "Clean walls/light switches",
    categoryId: "hallway",
    defaultFrequencyId: "monthly",
    defaultPts: 2,
  },
  {
    id: "hallway-dust-surfaces",
    defaultLabel: "Dust surfaces",
    categoryId: "hallway",
    defaultFrequencyId: "weekly",
    defaultPts: 2,
  },
  {
    id: "hallway-vacuum-mop-floors",
    defaultLabel: "Vacuum/mop floors",
    categoryId: "hallway",
    defaultFrequencyId: "weekly",
    defaultPts: 2,
  },
  {
    id: "hallway-clean-hallway-mirrors",
    defaultLabel: "Clean hallway mirrors",
    categoryId: "hallway",
    defaultFrequencyId: "weekly",
    defaultPts: 1,
  },
  {
    id: "hallway-wipe-hallway-baseboards",
    defaultLabel: "Wipe hallway baseboards",
    categoryId: "hallway",
    defaultFrequencyId: "monthly",
    defaultPts: 2,
  },
  {
    id: "hallway-organize-hallway-closet",
    defaultLabel: "Organize hallway closet",
    categoryId: "hallway",
    defaultFrequencyId: "quarterly",
    defaultPts: 3,
  },

  {
    id: "house-wipe-glass-doors",
    defaultLabel: "Wipe glass doors",
    categoryId: "house",
    defaultFrequencyId: "monthly",
    defaultPts: 2,
  },
  {
    id: "house-vacuum-vents",
    defaultLabel: "Vacuum vents",
    categoryId: "house",
    defaultFrequencyId: "quarterly",
    defaultPts: 2,
  },
  {
    id: "house-replace-air-filter",
    defaultLabel: "Replace air filter",
    categoryId: "house",
    defaultFrequencyId: "quarterly",
    defaultPts: 3,
  },
  {
    id: "house-test-smoke-detectors",
    defaultLabel: "Test smoke detectors",
    categoryId: "house",
    defaultFrequencyId: "monthly",
    defaultPts: 2,
  },
  {
    id: "house-replace-smoke-detector-batteries",
    defaultLabel: "Replace smoke detector batteries",
    categoryId: "house",
    defaultFrequencyId: "annual",
    defaultPts: 3,
  },
  {
    id: "house-clean-door-handles",
    defaultLabel: "Clean door handles",
    categoryId: "house",
    defaultFrequencyId: "weekly",
    defaultPts: 1,
  },
  {
    id: "house-wipe-baseboards",
    defaultLabel: "Wipe baseboards",
    categoryId: "house",
    defaultFrequencyId: "monthly",
    defaultPts: 2,
  },
  {
    id: "house-clean-windows",
    defaultLabel: "Clean windows",
    categoryId: "house",
    defaultFrequencyId: "quarterly",
    defaultPts: 3,
  },
  {
    id: "house-organize-storage-areas",
    defaultLabel: "Organize storage areas",
    categoryId: "house",
    defaultFrequencyId: "quarterly",
    defaultPts: 3,
  },
  {
    id: "house-clean-window-sills",
    defaultLabel: "Clean window sills",
    categoryId: "house",
    defaultFrequencyId: "monthly",
    defaultPts: 2,
  },
  {
    id: "house-wipe-electronics-remotes",
    defaultLabel: "Wipe electronics/remotes",
    categoryId: "house",
    defaultFrequencyId: "weekly",
    defaultPts: 2,
  },
];

export const lookupCategorySeeds: LookupCategoryDTO[] = [
  { id: "attic", label: "Attic", selectable: true },
  { id: "basement", label: "Basement", selectable: true },
  { id: "dining-area", label: "Dining Area", selectable: true },
  { id: "driveway", label: "Driveway", selectable: true },
  { id: "garage", label: "Garage", selectable: true },
  { id: "laundry-room", label: "Laundry Room", selectable: true },
  { id: "office", label: "Office", selectable: true },
  { id: "yard", label: "Yard", selectable: true },
  { id: "hallway", label: "Hallway", selectable: false },

  { id: "bathroom", label: "Bathroom", selectable: false },
  { id: "bedroom", label: "Bedroom", selectable: false },
  { id: "house", label: "House", selectable: false },
  { id: "kitchen", label: "Kitchen", selectable: false },
  { id: "living-room", label: "Living Room", selectable: false },
];

export const lookupFrequencySeeds: LookupFrequencyDTO[] = [
  { id: "daily", label: "Daily", intervalValue: 1, intervalUnit: "day", sortOrder: 1, active: true },
  { id: "weekly", label: "Weekly", intervalValue: 7, intervalUnit: "day", sortOrder: 2, active: true },
  { id: "monthly", label: "Monthly", intervalValue: 1, intervalUnit: "month", sortOrder: 3, active: true },
  { id: "quarterly", label: "Quarterly", intervalValue: 3, intervalUnit: "month", sortOrder: 4, active: true },
  { id: "semi_annually", label: "Semi-annually", intervalValue: 6, intervalUnit: "month", sortOrder: 5, active: true },
  { id: "annually", label: "Annually", intervalValue: 12, intervalUnit: "month", sortOrder: 6, active: true },
  { id: "seasonally", label: "Seasonally", intervalValue: 0, intervalUnit: "month", sortOrder: 7, active: true },
];
